### PR TITLE
Faster set context

### PR DESCRIPTION
**Pull request by Narayana108**
The old **set-context** command has become **activate** -  Used when never signed aks or gke before.

The **set-context** command is 1-3 seconds faster now.

### CODE REVIEW

**Review by michailbrynard — CHANGES_REQUESTED** [review]
@Narayana108 I see you've hardcoded some values for rdeploy to expect, such as our specific cluster names `production`, `ha-production` etc, in order to accomodate for Google or Azure's default cluster name conventions (gke_rehive-services_europe-west1-c_production, aks-westeurope-rehive-services-staging).

I think it would be better if these things weren't hardcoded. E.g. what if we decide to switch staging back to GKE or what if we want to use rdeploy with clusters on azure or gke with other names?

I think perhaps it would be better for us to have an rdeploy setup command that controls what the kubernetes contexts are labelled as. I'll have a look but I'm sure this should be configurable via gcloud and az cli. I.e. when the cluster is initially added it should be called 
{cloud-provider-name}-{cloud-provider-project}-{cloud-provider-region}-{cluster-name} so that we don't need to hard code things.

**Comment by michailbrynard** [comment]
On AKS, I see they have the `--context` parameter that allows us to specify the name https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_get_credentials on initial setup

**Comment by michailbrynard** [comment]
I don't see a similar option in gcloud's get-credentials function though. Another option would be to use rename the context on initial setup for google cloud then (maybe with https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-rename-context-em-) Else maybe there's an even better solution, but it would nice to avoid hardcoding expected names.

**Comment by Narayana108** [comment]
Greetings @michailbrynard  :),

Thank you for you wonderful feedback.

Two comments on your feedback.

1. It won't be tricky when switching back to GKE, the rdeploy app just reads the rdeploy.yaml, so it supports changing switching clusters.

2. When adding new clusters to rdeploy this happens very rarely and it will only take a minute to update rdeploy.

But yes, you are correct and I never thought of changing the cluster names to something predictable. And that would be much better ! I will look further into this. I think in future, If you dont mind I will try get more feedback when working on certain projects.

**Comment by michailbrynard** [comment]
I agree it's not too much effort to add new clusters, but it is nice to be able to use rdeploy in other contexts as well (you'll see it is an open source project and we've used at hackathons in the past to deploy non-rehive related projects) and so I prefer to avoid hardcoding rehive specific configs into the source code.

**Review by michailbrynard — APPROVED** [review]
This looks good, thanks @Narayana108

**Pull request merged**
